import type { CorrelationAction } from './correlate';
import { resolveSystemBotUser } from '@/lib/system-users';
import { addNoteService } from '@/lib/juridico/service';
import { createLogger } from '@/lib/logger';

const log = createLogger('correlation-actions');

/**
 * Apply correlation actions generated by the pure correlation engine.
 *
 * Each action is executed independently; failures are logged as non-fatal.
 * Note: addNoteService already triggers touchConsultationInteraction internally,
 * so we do not call it separately here.
 */
export async function applyCorrelationActions(actions: CorrelationAction[]): Promise<void> {
  for (const action of actions) {
    if (action.type === 'insert_note') {
      try {
        const botUserId = await resolveSystemBotUser();
        await addNoteService({
          entityType: 'consultation',
          entityId: action.consultationId,
          content: action.content,
          createdBy: botUserId,
          isEscritorioResponse: false,
        });
        log.info('Nota criada por correlacao de triagem.', { consultationId: action.consultationId });
      } catch (err) {
        log.warn(
          'Failed to apply correlation action (non-fatal).',
          { actionType: action.type },
          err instanceof Error ? err : undefined,
        );
      }
    } else {
      log.info('Correlacao ignorada.', { reason: action.reason });
    }
  }
}
