import type { CorrelationAction } from './correlate';
import { resolveSystemBotUser } from '@/lib/system-users';
import { addNoteService } from '@/lib/juridico/service';
import { createLogger } from '@/lib/logger';

const log = createLogger('correlation-actions');

/**
 * Apply correlation actions generated by the pure correlation engine.
 *
 * Each action is executed independently; failures are logged as non-fatal.
 * Note: addNoteService already triggers touchConsultationInteraction internally,
 * so we do not call it separately here.
 */
export async function applyCorrelationActions(actions: CorrelationAction[]): Promise<void> {
  const hasInsertNote = actions.some((action) => action.type === 'insert_note');
  let botUserId: number | undefined;

  if (hasInsertNote) {
    try {
      botUserId = await resolveSystemBotUser();
    } catch (err) {
      log.warn(
        'Failed to resolve system bot user (non-fatal, skipping notes).',
        {},
        err instanceof Error ? err : undefined,
      );
      // We can't insert notes without the bot user.
      // Other action types would still process, but right now insert_note is the only one.
      // The original code failed per-note if resolveSystemBotUser threw,
      // we just skip the note inserts instead.
    }
  }

  const promises = actions.map(async (action) => {
    if (action.type === 'insert_note') {
      if (botUserId === undefined) {
        return; // Bot user resolution failed; we logged it and skip safely
      }

      try {
        await addNoteService({
          entityType: 'consultation',
          entityId: action.consultationId,
          content: action.content,
          // Safe cast because we've checked for undefined above
          createdBy: botUserId as number,
          isEscritorioResponse: false,
        });
        log.info('Nota criada por correlacao de triagem.', { consultationId: action.consultationId });
      } catch (err) {
        log.warn(
          'Failed to apply correlation action (non-fatal).',
          { actionType: action.type },
          err instanceof Error ? err : undefined,
        );
      }
    } else {
      log.info('Correlacao ignorada.', { reason: action.reason });
    }
  });

  await Promise.all(promises);
}
