#!/usr/bin/env bash
# Cloud Agent install phase for the ASOF Intranet.
#
# Idempotent, non-interactive repository + PostgreSQL bootstrap. Runs after the
# repository is checked out. Safe to run repeatedly and against a cached/partial
# state, so every step is guarded. No long-running process is started here; the
# PostgreSQL daemon is (re)started per boot by .cursor/start.sh.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

PG_VERSION=16
DB_USER="${USER:-ubuntu}"
DEV_DB="asof_intranet"
TEST_DB="asof_intranet_test"
E2E_DB="asof_test"

log() { echo "[install] $*"; }

# 1. System dependency: PostgreSQL server + client (stable, so only install once).
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  log "installing PostgreSQL ${PG_VERSION}"
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql postgresql-client postgresql-contrib
fi

# 2. Ensure the cluster is running so we can provision roles/databases and migrate.
sudo pg_ctlcluster "$PG_VERSION" main start 2>/dev/null || true
for _ in $(seq 1 30); do
  pg_isready -h localhost -p 5432 >/dev/null 2>&1 && break
  sleep 1
done
pg_isready -h localhost -p 5432

# 3. Trust local TCP connections for the dev role. Dev-only convenience: the DB
#    is local to the agent VM and never holds production data.
HBA="/etc/postgresql/${PG_VERSION}/main/pg_hba.conf"
if [ -f "$HBA" ]; then
  sudo sed -i -E 's#^(host[[:space:]]+all[[:space:]]+all[[:space:]]+127\.0\.0\.1/32[[:space:]]+)scram-sha-256#\1trust#' "$HBA"
  sudo sed -i -E 's#^(host[[:space:]]+all[[:space:]]+all[[:space:]]+::1/128[[:space:]]+)scram-sha-256#\1trust#' "$HBA"
  sudo pg_ctlcluster "$PG_VERSION" main reload 2>/dev/null || true
fi

# 4. Login role matching the runtime OS user (used by DATABASE_URL and the E2E
#    setup, which derives its DB user from $USER) plus the local databases.
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1; then
  sudo -u postgres psql -c "CREATE ROLE \"${DB_USER}\" LOGIN SUPERUSER;"
fi
for db in "$DEV_DB" "$TEST_DB" "$E2E_DB"; do
  if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${db}'" | grep -q 1; then
    sudo -u postgres createdb -O "${DB_USER}" "${db}"
  fi
done

# 5. Local env files (gitignored). Secrets are generated once and preserved on
#    reruns so sessions/encryption stay stable across install invocations.
if [ ! -f .env.local ]; then
  log "writing .env.local"
  cat > .env.local <<EOF
# Generated by .cursor/install.sh for the Cloud Agent dev environment.
DATABASE_URL=postgres://${DB_USER}@localhost:5432/${DEV_DB}
DATABASE_MIGRATION_URL=postgres://${DB_USER}@localhost:5432/${DEV_DB}

SESSION_SECRET=$(openssl rand -hex 32)
ENCRYPTION_MASTER_KEY=$(openssl rand -hex 32)

SKIP_AUTH=true
DEV_USER_ID=1
DEV_USER_NAME="ASOF Dev User"
DEV_USER_EMAIL=dev@asof.local
DEV_USER_ROLE=admin
DEV_USER_MUST_CHANGE_PASSWORD=false

INITIAL_ADMIN_EMAIL=admin@example.invalid
INITIAL_ADMIN_PASSWORD=ChangeMe-2026!

LOG_LEVEL=info
EOF
fi

if [ ! -f .env.test.local ]; then
  log "writing .env.test.local"
  cat > .env.test.local <<EOF
# Generated by .cursor/install.sh — dedicated integration-test database.
DATABASE_URL=postgres://${DB_USER}@localhost:5432/${TEST_DB}
DATABASE_MIGRATION_URL=postgres://${DB_USER}@localhost:5432/${TEST_DB}

SESSION_SECRET=$(openssl rand -hex 32)
ENCRYPTION_MASTER_KEY=$(openssl rand -hex 32)

SKIP_AUTH=true
DEV_USER_ID=1
DEV_USER_EMAIL=dev@asof.local
DEV_USER_ROLE=admin
EOF
fi

# 6. Node dependencies, pinned to the lockfile.
log "npm ci"
npm ci

# 7. Apply migrations to the dev and integration-test databases (idempotent).
log "applying migrations (dev + test)"
npm run db:migrate
DATABASE_MIGRATION_URL="postgres://${DB_USER}@localhost:5432/${TEST_DB}" npx drizzle-kit migrate

# 8. Playwright browser used by the E2E suite (best effort; non-fatal).
log "installing Playwright chromium"
npx playwright install --with-deps chromium >/dev/null 2>&1 \
  || npx playwright install chromium >/dev/null 2>&1 \
  || log "Playwright browser install skipped"

# 9. Seed synthetic dev data only when the dev database is empty, so reruns do
#    not duplicate rows.
DEV_URL="postgres://${DB_USER}@localhost:5432/${DEV_DB}"
COUNT="$(psql "$DEV_URL" -tAc "SELECT count(*) FROM associates" 2>/dev/null || echo 0)"
if [ "${COUNT:-0}" = "0" ]; then
  log "seeding synthetic dev data"
  npm run db:seed:dev
else
  log "dev database already has ${COUNT} associates; skipping seed"
fi

log "complete"
