#!/usr/bin/env bash
# Cloud Agent install phase for the ASOF Intranet.
#
# Idempotent, non-interactive repository bootstrap. Runs after checkout. Safe to
# run repeatedly and against cached/partial state. No long-running process is
# started here; PostgreSQL is (re)started per boot by .cursor/start.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

DB_USER="${USER:-ubuntu}"
DEV_DB="asof_intranet"
TEST_DB="asof_intranet_test"

log() { echo "[cloud-agent] $*"; }

log "Provisioning PostgreSQL..."
bash "$SCRIPT_DIR/provision-postgres.sh"

write_env_file() {
  local path="$1"
  local database="$2"
  if [[ -f "$path" ]]; then
    return 0
  fi
  log "Writing ${path}"
  cat > "$path" <<EOF
# Generated by .cursor/install.sh for the Cloud Agent local-first setup.
# Daily development uses localhost PostgreSQL + synthetic seed (docs/environments.md).
# Do not point these files at Neon/Vercel Storage; that is an LGPD exception.
DATABASE_URL=postgres://${DB_USER}@localhost:5432/${database}
DATABASE_MIGRATION_URL=postgres://${DB_USER}@localhost:5432/${database}

SESSION_SECRET=$(openssl rand -hex 32)
ENCRYPTION_MASTER_KEY=$(openssl rand -hex 32)

SKIP_AUTH=true
DEV_USER_ID=1
DEV_USER_NAME="ASOF Dev User"
DEV_USER_EMAIL=dev@asof.local
DEV_USER_ROLE=admin
DEV_USER_MUST_CHANGE_PASSWORD=false

INITIAL_ADMIN_EMAIL=admin@example.invalid
INITIAL_ADMIN_PASSWORD=ChangeMe-2026!

LOG_LEVEL=info
EOF
}

write_env_file .env.local "$DEV_DB"
write_env_file .env.test.local "$TEST_DB"

log "Installing npm dependencies..."
npm ci

log "Applying migrations (dev + integration-test)..."
npm run db:migrate
DATABASE_MIGRATION_URL="postgres://${DB_USER}@localhost:5432/${TEST_DB}" npx drizzle-kit migrate

log "Installing Playwright chromium (best-effort)..."
npx playwright install --with-deps chromium >/dev/null 2>&1 \
  || npx playwright install chromium >/dev/null 2>&1 \
  || log "Playwright browser install skipped"

COUNT="$(psql -h localhost -d "$DEV_DB" -tAc "SELECT count(*) FROM associates" 2>/dev/null || echo 0)"
if [[ "${COUNT:-0}" == "0" ]]; then
  log "Seeding synthetic dev data..."
  npm run db:seed:dev
else
  log "Dev database already has ${COUNT} associates; skipping seed"
fi

log "Install complete."
