```json
{
  "postos": {
    "Africa": [
      { "posto": "(E) Abidjã", "pais": "Costa do Marfim", "ef": 17 },
      { "posto": "(E) Abuja", "pais": "Nigéria", "ef": 19 },
      { "posto": "(E) Acra", "pais": "Gana", "ef": 16 },
      { "posto": "(E) Adis Abeba", "pais": "Etiópia", "ef": 22 },
      { "posto": "(E) Argel", "pais": "Argélia", "ef": 22 },
      { "posto": "(E) Bamako", "pais": "Mali", "ef": 13 },
      { "posto": "(E) Bissau", "pais": "Guiné Bissau", "ef": 33 },
      { "posto": "(E) Brazzaville", "pais": "Congo", "ef": 16 },
      { "posto": "(E) Cairo", "pais": "Egito", "ef": 32 },
      { "posto": "(E) Cartum", "pais": "Sudão", "ef": 6 },
      { "posto": "(CG) Cidade do Cabo", "pais": "África do Sul", "ef": 11 },
      { "posto": "(E) Conacri", "pais": "Guiné", "ef": 13 },
      { "posto": "(E) Cotonou", "pais": "Benin", "ef": 14 },
      { "posto": "(E) Dacar", "pais": "Senegal", "ef": 19 },
      { "posto": "(E) Dar es Salaam", "pais": "Tanzânia", "ef": 12 },
      { "posto": "(E) Gaborone", "pais": "Botsuana", "ef": 11 },
      { "posto": "(E) Harare", "pais": "Zimbábue", "ef": 15 },
      { "posto": "(E) Iaundê", "pais": "Camarões", "ef": 12 },
      { "posto": "(E) Kigali", "pais": "Ruanda", "ef": 7 },
      { "posto": "(E) Kinshasa", "pais": "Rep. Dem. do Congo", "ef": 12 },
      { "posto": "(CG) Lagos", "pais": "Nigéria", "ef": 20 },
      { "posto": "(E) Libreville", "pais": "Gabão", "ef": 11 },
      { "posto": "(E) Lomé", "pais": "Togo", "ef": 15 },
      { "posto": "(E) Luanda", "pais": "Angola", "ef": 43 },
      { "posto": "(CG) Luanda", "pais": "Angola", "ef": 9 },
      { "posto": "(E) Lusaca", "pais": "Zâmbia", "ef": 14 },
      { "posto": "(E) Malabo", "pais": "Guiné Equatorial", "ef": 18 },
      { "posto": "(E) Maputo", "pais": "Moçambique", "ef": 44 },
      { "posto": "(E) Nairóbi", "pais": "Quênia", "ef": 24 },
      { "posto": "(E) Nouakchott", "pais": "Mauritânia", "ef": 15 },
      { "posto": "(E) Praia", "pais": "Cabo Verde", "ef": 25 },
      { "posto": "(E) Pretória", "pais": "África do Sul", "ef": 38 },
      { "posto": "(E) Rabat", "pais": "Marrocos", "ef": 25 },
      { "posto": "(E) São Tomé", "pais": "São Tomé e Príncipe", "ef": 17 },
      { "posto": "(E) Túnis", "pais": "Tunísia", "ef": 19 },
      { "posto": "(E) Uagadugu", "pais": "Burkina Faso", "ef": 20 },
      { "posto": "(E) Windhoek", "pais": "Namíbia", "ef": 8 }
    ],
    "AmericaCentralCaribe": [
      { "posto": "(E) Belmopan", "pais": "Belize", "ef": 11 },
      { "posto": "(E) Bridgetown", "pais": "Barbados", "ef": 13 },
      { "posto": "(E) Castries", "pais": "Santa Lúcia", "ef": 7 },
      { "posto": "(E) Guatemala", "pais": "Guatemala", "ef": 23 },
      { "posto": "(E) Havana", "pais": "Cuba", "ef": 32 },
      { "posto": "(E) Kingston", "pais": "Jamaica", "ef": 13 },
      { "posto": "(E) Kingstown", "pais": "São Vicente e Granadinas", "ef": 8 },
      { "posto": "(E) Manágua", "pais": "Nicarágua", "ef": 30 },
      { "posto": "(E) Nassau", "pais": "Bahamas", "ef": 8 },
      { "posto": "(E) Panamá", "pais": "Panamá", "ef": 24 },
      { "posto": "(E) Port of Spain", "pais": "Trinidad e Tobago", "ef": 16 },
      { "posto": "(E) Porto Príncipe", "pais": "Haiti", "ef": 37 },
      { "posto": "(E) São Domingos", "pais": "República Dominicana", "ef": 23 },
      { "posto": "(E) São José", "pais": "Costa Rica", "ef": 21 },
      { "posto": "(E) São Salvador", "pais": "El Salvador", "ef": 16 },
      { "posto": "(E) Tegucigalpa", "pais": "Honduras", "ef": 16 }
    ],
    "AmericaNorte": [
      { "posto": "(CG) Atlanta", "pais": "EUA", "ef": 25 },
      { "posto": "(CG) Boston", "pais": "EUA", "ef": 39 },
      { "posto": "(CG) Chicago", "pais": "EUA", "ef": 28 },
      { "posto": "(CG) Hartford", "pais": "EUA", "ef": 17 },
      { "posto": "(CG) Houston", "pais": "EUA", "ef": 22 },
      { "posto": "(CG) Los Angeles", "pais": "EUA", "ef": 39 },
      { "posto": "(CG) Miami", "pais": "EUA", "ef": 50 },
      { "posto": "(D) Montreal", "pais": "Canadá", "ef": 14 },
      { "posto": "(CG) Montreal", "pais": "Canadá", "ef": 19 },
      { "posto": "(CG) México", "pais": "México", "ef": 6 },
      { "posto": "(E) México", "pais": "México", "ef": 54 },
      { "posto": "(CG) Nova York", "pais": "EUA", "ef": 65 },
      { "posto": "(D) Nova York", "pais": "EUA", "ef": 54 },
      { "posto": "(EF) Nova York", "pais": "EUA", "ef": 42 },
      { "posto": "(CG) Orlando", "pais": "EUA", "ef": 14 },
      { "posto": "(E) Ottawa", "pais": "Canadá", "ef": 25 },
      { "posto": "(CG) São Francisco", "pais": "EUA", "ef": 29 },
      { "posto": "(CG) Toronto", "pais": "Canadá", "ef": 25 },
      { "posto": "(CG) Vancouver", "pais": "Canadá", "ef": 19 },
      { "posto": "(CG) Washington", "pais": "EUA", "ef": 31 },
      { "posto": "(E) Washington", "pais": "EUA", "ef": 65 },
      { "posto": "(D) Washington", "pais": "EUA", "ef": 27 }
    ],
    "AmericaSul": [
      { "posto": "(VC) Artigas", "pais": "Uruguai", "ef": 10 },
      { "posto": "(E) Assunção", "pais": "Paraguai", "ef": 57 },
      { "posto": "(CG) Assunção", "pais": "Paraguai", "ef": 22 },
      { "posto": "(E) Bogotá", "pais": "Colômbia", "ef": 41 },
      { "posto": "(CG) Buenos Aires", "pais": "Argentina", "ef": 28 },
      { "posto": "(E) Buenos Aires", "pais": "Argentina", "ef": 99 },
      { "posto": "(E) Caracas", "pais": "Venezuela", "ef": 34 },
      { "posto": "(C) Chuy", "pais": "Uruguai", "ef": 4 },
      { "posto": "(CG) Ciudad del Este", "pais": "Paraguai", "ef": 19 },
      { "posto": "(C) Ciudad Guayana", "pais": "Venezuela", "ef": 0 },
      { "posto": "(C) Cobija", "pais": "Bolívia", "ef": 5 },
      { "posto": "(CG) Cochabamba", "pais": "Bolívia", "ef": 12 },
      { "posto": "(VC) Concepción", "pais": "Paraguai", "ef": 4 },
      { "posto": "(CG) Córdoba", "pais": "Argentina", "ef": 11 },
      { "posto": "(VC) Encarnación", "pais": "Paraguai", "ef": 7 },
      { "posto": "(E) Georgetown", "pais": "Guiana", "ef": 23 },
      { "posto": "(C) Guayaramerín", "pais": "Bolívia", "ef": 5 },
      { "posto": "(VC) Iquitos", "pais": "Peru", "ef": 1 },
      { "posto": "(E) La Paz", "pais": "Bolívia", "ef": 59 },
      { "posto": "(VC) Lethem", "pais": "Guiana", "ef": 4 },
      { "posto": "(VC) Letícia", "pais": "Colômbia", "ef": 6 },
      { "posto": "(E) Lima", "pais": "Peru", "ef": 67 },
      { "posto": "(CG) Mendoza", "pais": "Argentina", "ef": 11 },
      { "posto": "(E) Montevidéu", "pais": "Uruguai", "ef": 40 },
      { "posto": "(CG) Montevidéu", "pais": "Uruguai", "ef": 22 },
      { "posto": "(D) Montevidéu", "pais": "Uruguai", "ef": 27 },
      { "posto": "(E) Paramaribo", "pais": "Suriname", "ef": 39 },
      { "posto": "(C) Paso de los Libres", "pais": "Argentina", "ef": 5 },
      { "posto": "(C) Pedro Juan Caballero", "pais": "Paraguai", "ef": 7 },
      { "posto": "(C) Puerto Iguazú", "pais": "Argentina", "ef": 7 },
      { "posto": "(C) Puerto Quijarro", "pais": "Bolívia", "ef": 5 },
      { "posto": "(E) Quito", "pais": "Equador", "ef": 33 },
      { "posto": "(CG) Rivera", "pais": "Uruguai", "ef": 11 },
      { "posto": "(VC) Río Branco", "pais": "Uruguai", "ef": 3 },
      { "posto": "(C) Saint-Georges-de-l'Oyapock", "pais": "Guiana Francesa", "ef": 3 },
      { "posto": "(C) Saltos del Guairá", "pais": "Paraguai", "ef": 6 },
      { "posto": "(CG) Santa Cruz de la Sierra", "pais": "Bolívia", "ef": 30 },
      { "posto": "(VC) Santa Elena de Uairén", "pais": "Venezuela", "ef": 6 },
      { "posto": "(CG) Santiago", "pais": "Chile", "ef": 16 },
      { "posto": "(E) Santiago", "pais": "Chile", "ef": 45 }
    ],
    "AsiaOrienteMedio": [
      { "posto": "(E) Abu Dhabi", "pais": "Emirados Árabes Unidos", "ef": 22 },
      { "posto": "(E) Amã", "pais": "Jordânia", "ef": 20 },
      { "posto": "(E) Astana", "pais": "Cazaquistão", "ef": 14 },
      { "posto": "(E) Bagdá", "pais": "Iraque", "ef": 9 },
      { "posto": "(E) Bangkok", "pais": "Tailândia", "ef": 27 },
      { "posto": "(E) Beirute", "pais": "Líbano", "ef": 41 },
      { "posto": "(CG) Cantão", "pais": "China", "ef": 21 },
      { "posto": "(CG) Chengdu", "pais": "China", "ef": 15 },
      { "posto": "(E) Colombo", "pais": "Sri Lanka", "ef": 13 },
      { "posto": "(E) Daca", "pais": "Bangladesh", "ef": 14 },
      { "posto": "(E) Damasco", "pais": "Síria", "ef": 15 },
      { "posto": "(E) Doha", "pais": "Catar", "ef": 13 },
      { "posto": "(E) Díli", "pais": "Timor Leste", "ef": 12 },
      { "posto": "(CG) Hamamatsu", "pais": "Japão", "ef": 23 },
      { "posto": "(E) Hanói", "pais": "Vietnã", "ef": 22 },
      { "posto": "(CG) Hong Kong", "pais": "HongKong", "ef": 13 },
      { "posto": "(E) Islamabad", "pais": "Paquistão", "ef": 14 },
      { "posto": "(E) Jacarta", "pais": "Indonésia", "ef": 26 },
      { "posto": "(D) Jacarta", "pais": "Indonésia", "ef": 2 },
      { "posto": "(E) Katmandu", "pais": "Nepal", "ef": 15 },
      { "posto": "(E) Kuala Lumpur", "pais": "Malásia", "ef": 23 },
      { "posto": "(E) Kuwait", "pais": "Kuaite", "ef": 18 },
      { "posto": "(E) Manama", "pais": "Bareine", "ef": 11 },
      { "posto": "(E) Manila", "pais": "Filipinas", "ef": 23 },
      { "posto": "(E) Mascate", "pais": "Omã", "ef": 16 },
      { "posto": "(CG) Mumbai", "pais": "Índia", "ef": 12 },
      { "posto": "(CG) Nagoia", "pais": "Japão", "ef": 42 },
      { "posto": "(E) Nova Delhi", "pais": "Índia", "ef": 37 },
      { "posto": "(E) Pequim", "pais": "China", "ef": 69 },
      { "posto": "(E) Phnom Penh", "pais": "Camboja", "ef": 2 },
      { "posto": "(E) Pyongyang", "pais": "Coreia do Norte", "ef": 11 },
      { "posto": "(ER) Ramala", "pais": "Palestina", "ef": 16 },
      { "posto": "(E) Riade", "pais": "Arábia Saudita", "ef": 23 },
      { "posto": "(E) Seul", "pais": "Coreia do Sul", "ef": 25 },
      { "posto": "(E) Singapura", "pais": "Singapura", "ef": 22 },
      { "posto": "(EC) Taipé", "pais": "Taiwan", "ef": 16 },
      { "posto": "(E) Teerã", "pais": "Irã", "ef": 21 },
      { "posto": "(E) Tel Aviv", "pais": "Israel", "ef": 29 },
      { "posto": "(E) Tóquio", "pais": "Japão", "ef": 58 },
      { "posto": "(CG) Tóquio", "pais": "Japão", "ef": 40 },
      { "posto": "(CG) Xangai", "pais": "China", "ef": 30 },
      { "posto": "(E) Yangon", "pais": "Myanmar", "ef": 16 }
    ],
    "Europa": [
      { "posto": "(CG) Amsterdã", "pais": "Países Baixos", "ef": 25 },
      { "posto": "(E) Ancara", "pais": "Turquia", "ef": 25 },
      { "posto": "(E) Atenas", "pais": "Grécia", "ef": 20 },
      { "posto": "(E) Baku", "pais": "Azerbaijão", "ef": 13 },
      { "posto": "(CG) Barcelona", "pais": "Espanha", "ef": 37 },
      { "posto": "(E) Belgrado", "pais": "Sérvia", "ef": 19 },
      { "posto": "(E) Berlim", "pais": "Alemanha", "ef": 59 },
      { "posto": "(E) Berna", "pais": "Suíça", "ef": 16 },
      { "posto": "(E) Bratislava", "pais": "Eslováquia", "ef": 14 },
      { "posto": "(CG) Bruxelas", "pais": "Bélgica", "ef": 27 },
      { "posto": "(E) Bruxelas", "pais": "Bélgica", "ef": 19 },
      { "posto": "(D) Bruxelas", "pais": "Bélgica", "ef": 31 },
      { "posto": "(E) Bucareste", "pais": "Romênia", "ef": 13 },
      { "posto": "(E) Budapeste", "pais": "Hungria", "ef": 17 },
      { "posto": "(CG) Caiena", "pais": "França", "ef": 16 },
      { "posto": "(E) Copenhague", "pais": "Dinamarca", "ef": 19 },
      { "posto": "(E) Dublin", "pais": "Irlanda", "ef": 22 },
      { "posto": "(CG) Edimburgo", "pais": "Reino Unido", "ef": 12 },
      { "posto": "(E) Estocolmo", "pais": "Suécia", "ef": 27 },
      { "posto": "(CG) Faro", "pais": "Portugal", "ef": 22 },
      { "posto": "(CG) Frankfurt", "pais": "Alemanha", "ef": 20 },
      { "posto": "(CG) Genebra", "pais": "Suíça", "ef": 22 },
      { "posto": "(D) Genebra", "pais": "Suíça", "ef": 35 },
      { "posto": "(D) Genebra", "pais": "Suíça", "ef": 39 },
      { "posto": "(D) Genebra DELBRASDESARM", "pais": "Suíça", "ef": 10 },
      { "posto": "(E) Haia", "pais": "Países Baixos", "ef": 28 },
      { "posto": "(E) Helsinque", "pais": "Finlândia", "ef": 20 },
      { "posto": "(E) Ierevan", "pais": "Armênia", "ef": 14 },
      { "posto": "(CG) Istambul", "pais": "Turquia", "ef": 17 },
      { "posto": "(E) Kiev", "pais": "Ucrânia", "ef": 14 },
      { "posto": "(CG) Lisboa", "pais": "Portugal", "ef": 48 },
      { "posto": "(D) Lisboa", "pais": "Portugal", "ef": 16 },
      { "posto": "(E) Lisboa", "pais": "Portugal", "ef": 48 },
      { "posto": "(E) Liubliana", "pais": "Eslovênia", "ef": 16 },
      { "posto": "(D) Londres", "pais": "Reino Unido", "ef": 3 },
      { "posto": "(E) Londres", "pais": "Reino Unido", "ef": 61 },
      { "posto": "(CG) Londres", "pais": "Reino Unido", "ef": 36 },
      { "posto": "(CG) Madri", "pais": "Espanha", "ef": 31 },
      { "posto": "(E) Madri", "pais": "Espanha", "ef": 48 },
      { "posto": "(CG) Marselha", "pais": "França", "ef": 21 },
      { "posto": "(CG) Milão", "pais": "Itália", "ef": 35 },
      { "posto": "(E) Minsk", "pais": "Belarus", "ef": 12 },
      { "posto": "(E) Moscou", "pais": "Rússia", "ef": 52 },
      { "posto": "(CG) Munique", "pais": "Alemanha", "ef": 23 },
      { "posto": "(E) Nicósia", "pais": "Chipre", "ef": 13 },
      { "posto": "(E) Oslo", "pais": "Noruega", "ef": 19 },
      { "posto": "(E) Paris", "pais": "França", "ef": 62 },
      { "posto": "(D) Paris", "pais": "França", "ef": 20 },
      { "posto": "(CG) Paris", "pais": "França", "ef": 36 },
      { "posto": "(D) Paris", "pais": "França", "ef": 7 },
      { "posto": "(CG) Porto", "pais": "Portugal", "ef": 38 },
      { "posto": "(E) Praga", "pais": "Rep. Tcheca", "ef": 20 },
      { "posto": "(D) Roma", "pais": "Itália", "ef": 23 },
      { "posto": "(CG) Roma", "pais": "Itália", "ef": 28 },
      { "posto": "(E) Roma", "pais": "Itália", "ef": 69 },
      { "posto": "(E) Sarajevo", "pais": "Bósnia-Herzegovina", "ef": 14 },
      { "posto": "(E) Sófia", "pais": "Bulgária", "ef": 18 },
      { "posto": "(E) Talin", "pais": "Estônia", "ef": 11 },
      { "posto": "(E) Tbilisi", "pais": "Geórgia", "ef": 15 },
      { "posto": "(E) Tirana", "pais": "Albânia", "ef": 14 },
      { "posto": "(E) Varsóvia", "pais": "Polônia", "ef": 22 },
      { "posto": "(E) Vaticano", "pais": "Vaticano", "ef": 22 },
      { "posto": "(E) Viena", "pais": "Áustria", "ef": 32 },
      { "posto": "(D) Viena", "pais": "Áustria", "ef": 14 },
      { "posto": "(E) Zagreb", "pais": "Croácia", "ef": 17 },
      { "posto": "(CG) Zurique", "pais": "Suíça", "ef": 17 }
    ],
    "Oceania": [
      { "posto": "(E) Camberra", "pais": "Austrália", "ef": 25 },
      { "posto": "(CG) Sydney", "pais": "Austrália", "ef": 25 },
      { "posto": "(E) Wellington", "pais": "Nova Zelândia", "ef": 16 }
    ]
  }
}
```

