name: Cleanup Neon Preview Branch

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  delete-branch:
    name: Delete Neon Preview Branch
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon preview branch
        uses: neondatabase/delete-branch-action@4468d825d5a88ef4012f1705a82f02ec3072f776 # v3.2.1
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/${{ github.head_ref }}
          api_key: ${{ secrets.NEON_API_KEY }}
